blueprint:
  name: Send Single Entity Data via MQTT
  description: This blueprint sends data from a single entity via MQTT
  domain: automation
  input:
    entity:
      name: Entity
      description: The entity to monitor
      selector:
        entity:
          domain: sensor
    icon:
      name: Icon
      description: The icon to include in the payload
      selector:
        text:
    mqtt_broker:
      name: MQTT Broker
      description: The MQTT broker address
      selector:
        text:
    mqtt_port:
      name: MQTT Port
      description: The MQTT broker port
      default: 1883
      selector:
        number:
          min: 1
          max: 65535
    mqtt_username:
      name: MQTT Username
      description: The MQTT broker username
      selector:
        text:
    mqtt_password:
      name: MQTT Password
      description: The MQTT broker password
      selector:
        text:
    mqtt_topic:
      name: MQTT Topic
      description: The MQTT topic to publish data to
      default: "ulanzi/custom/solar"
      selector:
        text:

trigger:
  - platform: state
    entity_id: !input entity

action:
  - service: mqtt.publish
    data:
      topic: !input mqtt_topic
      payload_template: >
        {
          "text": "{{ states(input.entity) }}",
          "icon": "{{ input.icon }}",
          "lifetime": "30"
        }
      qos: 0
      retain: false
